/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Trip { 
    readonly id?: number;
    readonly time?: string;
    store?: number | null;
    list?: number | null;
    count?: number;
    finish_time?: string | null;
    readonly label?: string;
    notes?: string | null;
}

