# Generated by Django 3.2.3 on 2021-05-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
