# Generated by Django 3.2.3 on 2021-05-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20210522_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='standard_count',
            new_name='last_count',
        ),
    ]
