# Generated by Django 3.2.3 on 2021-05-22 23:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_alter_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.list'),
            preserve_default=False,
        ),
    ]
