# Generated by Django 3.2.3 on 2021-05-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20210522_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy',
            field=models.BooleanField(default=True),
        ),
    ]
