# Generated by Django 3.2.3 on 2021-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20211023_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_bought',
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
