# Generated by Django 3.2.3 on 2021-10-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_alter_list_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ean',
            field=models.TextField(blank=True, null=True),
        ),
    ]
