# Generated by Django 3.2.3 on 2021-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_alter_item_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
