# Generated by Django 3.2.3 on 2021-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_trip_finish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'get_latest_by': ['-time']},
        ),
        migrations.AddField(
            model_name='item',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
