# Generated by Django 3.2.3 on 2021-10-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_auto_20211025_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='list',
        ),
    ]
