# Generated by Django 3.2.3 on 2021-11-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_auto_20211114_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='description',
        ),
    ]
