# Generated by Django 3.2.3 on 2021-11-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0020_rename_text_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='total',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_currency',
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='list.trip'),
        ),
    ]
