# Generated by Django 3.2.3 on 2021-11-15 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_auto_20211114_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
