# Generated by Django 3.2.3 on 2021-11-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0026_auto_20211116_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandItem',
            new_name='SKU',
        ),
    ]
