# Generated by Django 3.2.3 on 2021-11-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0027_rename_branditem_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['description']},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['description'], 'verbose_name_plural': 'SKUs'},
        ),
        migrations.AlterField(
            model_name='sku',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='list.item'),
        ),
    ]
