# Generated by Django 3.2.3 on 2021-11-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0028_auto_20211125_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_count',
        ),
    ]
