# Generated by Django 3.2.3 on 2021-11-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0029_auto_20211125_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='brand_item',
            new_name='sku',
        ),
    ]
