# Generated by Django 3.2.3 on 2021-11-29 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0030_rename_brand_item_lineitem_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'get_latest_by': ['-receipt__time']},
        ),
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
