# Generated by Django 3.2.3 on 2021-12-04 22:22

from django.db import migrations, models
import django.db.models.deletion

def migrate_catalog(apps, schema_editor):
    Item = apps.get_model("list", "Item")
    CatalogItem = apps.get_model("list", "CatalogItem")
    SKU = apps.get_model("list", "SKU")

    all_items = Item.objects.all()

    for item in all_items:
        catalog_item = CatalogItem.objects.create(
            description=item.description,
            created_at=item.created_at,
        )
        item.catalog_item = catalog_item
        item.save()

    all_skus = SKU.objects.all()

    for sku in all_skus:
        if sku.item:
            sku.catalog_item = sku.item.catalog_item
            sku.save()



class Migration(migrations.Migration):

    dependencies = [
        ('list', '0031_auto_20211129_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='list.catalogitem'),
        ),
        migrations.AddField(
            model_name='sku',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='list.catalogitem'),
        ),
        # run migration script here
        migrations.RunPython(migrate_catalog),
        migrations.RemoveField(
            model_name='item',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='item',
            name='index',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='item',
        ),
    ]
