# Generated by Django 3.2.3 on 2021-12-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0032_catalog_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['index']},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='count',
        ),
        migrations.AddField(
            model_name='item',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
